$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json
default: true
MD003:
  style: atx
MD007:
  indent: 4
no-inline-html:
  allowed_elements:
    - br
    - img
MD013:
  line_length: 125
MD041: false